model:
  model_name: "m-a-p/music2vec-v1"
  hidden_size: 768
  num_labels: 8

optimizer:
  optimizer_name: "AdamW"
  lr: 3e-5
  weight_decay: 1e-5
  scheduler: "linear"
  warmup_steps: 0.1

dataset:
  audio_dir: "fma_small"
  train:
    train_csv: "csv_files/train.csv"
  val:
    val_csv: "csv_files/val.csv"
  test:
    test_csv: "csv_files/test.csv"

loss:
  type: "cross-entropy"

training:
  batch_size: 16
  epochs: 10
  seed: 42
  dropout_prob: 0.3
  patience: 5
  checkpoint_dir: "checkpoints/"

experiment:
  log: "wandb"
  log_every_n_steps: 10
  experiment_group: "sta-armeniakos-athens-university-of-economics-and-business"
  project: "deep-learning"
  experiment_name: "experiment-lr-1e-3"

distortion:
  model_name: "mtg-upf/discogs-maest-10s-pw-129e"
  audios_csv: "gtzan.csv"
  audio_dir: "gtzan/"
  target_dir: "distortion/"
  fad_txt: "fad.txt"
  genre: "rock"
  norm_lambda: 1e-3
  loss: "kl-divergence"
  threshold: 0.4
  max_number_of_steps: 100
  optimizer:
    optimizer_name: "AdamW"
    lr: 1e-5
    weight_decay: 0.0






