model:
  model_name: "facebook/wav2vec2-base"
  hidden_size: 768
  num_labels: 8

optimizer:
  optimizer_name: "AdamW"
  lr: "1e-5"
  weight_decay: ""
  scheduler: "StepLR"
  scheduler_steps: ""

loss:
  name: "cross-entropy"

dataset:
  train_dir: "data/train"
  val_dir: "data/val"
  test_dir: "data/test"

training:
  lr: ""
  optimizer: ""
  epochs: ""
  dropout_prob: ""
  early_stopping: ""
  checkpoint_epochs: ""
  checkpoint_dir: "checkpoints/"

experiment:
  log: "wandb"
  log_every_n_steps: 30
  experiment_group: "sta-armeniakos-athens-university-of-economics-and-business"
  project: "deep-learning"
  experiment_name: "baseline-experiment"





