model:
  model_name: "facebook/wav2vec2-base"
  hidden_size: 768
  num_labels: 8

optimizer:
  optimizer_name: "AdamW"
  lr: "1e-5"
  weight_decay: ""
  scheduler: "StepLR"
  scheduler_steps: ""

loss:
  name: "cross-entropy"

dataset:
  audio_dir: "audios"
  train:
    train_csv: "csv_files/train.csv"
  val:
    val_csv: "csv_files/val.csv"
  test:
    test_csv: "csv_files/test.csv"

training:
  lr: ""
  optimizer: ""
  epochs: ""
  dropout_prob: ""
  early_stopping: ""
  checkpoint_epochs: ""
  checkpoint_dir: "checkpoints/"

experiment:
  log: "wandb"
  log_every_n_steps: 30
  experiment_group: "sta-armeniakos-athens-university-of-economics-and-business"
  project: "deep-learning"
  experiment_name: "baseline-experiment"

distortion:
  genre: "rock"



