model:
  model_name: "facebook/wav2vec2-base"
  hidden_size: 768
  num_labels: 8

optimizer:
  optimizer_name: "AdamW"
  lr: 1e-4
  weight_decay: 1e-5
  scheduler: "linear"
  warmup_steps: 0.1


dataset:
  audio_dir: "fma_small"
  train:
    train_csv: "csv_files/train.csv"
  val:
    val_csv: "csv_files/val.csv"
  test:
    test_csv: "csv_files/test.csv"

loss:
  type: "cross-entropy"

training:
  batch_size: 32
  epochs: 10
  dropout_prob: 0.4
  patience: 5
  checkpoint_dir: "checkpoints/"

experiment:
  log: "wandb"
  log_every_n_steps: 10
  experiment_group: "sta-armeniakos-athens-university-of-economics-and-business"
  project: "deep-learning"
  experiment_name: "baseline-experiment"

distortion:
  genre: "rock"



